# Generated by Django 2.0.4 on 2019-03-05 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20180509_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestats',
            name='user',
        ),
        migrations.AddField(
            model_name='snakeversion',
            name='code_compiled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='snakegame',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='active_snake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.SnakeVersion'),
        ),
        migrations.DeleteModel(
            name='LiveStats',
        ),
    ]
