# Generated by Django 2.0.4 on 2019-03-09 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20190305_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snakeversion',
            name='code_compiled',
        ),
        migrations.AddField(
            model_name='snakeversion',
            name='build_log',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='snakeversion',
            name='compile_state',
            field=models.CharField(choices=[('not_compiled', 'Not compiled yet'), ('successful', 'Compiled successfully'), ('failed', 'Compilation failed')], default='not_compiled', max_length=12),
        ),
    ]
