# Generated by Django 2.0.4 on 2019-04-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_livestats'),
    ]

    operations = [
        migrations.AddField(
            model_name='snakegame',
            name='maximum_mass',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
