# Generated by Django 2.0.4 on 2019-05-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_snakegame_maximum_mass'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='persistent_data',
            field=models.BinaryField(blank=True, max_length=1048576, null=True),
        ),
    ]
