# Generated by Django 2.2.17 on 2022-01-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_userprofile_persistent_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=16, null=True)),
                ('readable_name', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'get_latest_by': 'created',
                'unique_together': {('slug', 'readable_name')},
            },
        ),
    ]
