# Generated by Django 2.2.17 on 2022-01-08 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_programminglanguage'),
    ]

    operations = [
        migrations.AddField(
            model_name='programminglanguage',
            name='file_extension',
            field=models.CharField(default='txt', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snakeversion',
            name='programming_language',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='core.ProgrammingLanguage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='programminglanguage',
            name='readable_name',
            field=models.CharField(default='?', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='programminglanguage',
            name='slug',
            field=models.CharField(default='?', max_length=16),
            preserve_default=False,
        ),
    ]
