# Generated by Django 2.2.17 on 2022-04-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20220108_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='programminglanguage',
            name='editor_mode',
            field=models.CharField(default='c_cpp', max_length=32),
            preserve_default=False,
        ),
    ]
